//
//  TodayViewController.swift
//  Today
//
//  Created by Mike Singleton on 12/23/14.
//  Copyright (c) 2014 Mike Singleton. All rights reserved.
//

import UIKit
import NotificationCenter

@objc(TodayViewController)

class TodayViewController: UIViewController, NCWidgetProviding {
        
    override func viewDidLoad() {
        super.viewDidLoad()

        let subview = UIView()
        subview.backgroundColor = UIColor.greenColor()
        view.addSubview(subview)
        
        // Set the height of the subview, and priority to 999 (making it 1000 conflicts with the 
        // UIView-Encapsulated-Layout-Height constraint generated by the system)
        let heightConstraint = NSLayoutConstraint(item: subview, attribute: NSLayoutAttribute.Height, relatedBy: NSLayoutRelation.Equal, toItem: nil, attribute: NSLayoutAttribute.NotAnAttribute, multiplier: 1, constant: 80)
        heightConstraint.priority = 999
        
        // Add top and bottom constrints of the subview to the layout guides. This will glue the superview
        // to the top and bottom, forcing it to expand to the subview height
        subview.setTranslatesAutoresizingMaskIntoConstraints(false)
        view.addConstraints([
            heightConstraint,
            NSLayoutConstraint(item: subview, attribute: NSLayoutAttribute.Top, relatedBy: NSLayoutRelation.Equal, toItem: self.topLayoutGuide, attribute: NSLayoutAttribute.Bottom, multiplier: 1, constant: 0),
            NSLayoutConstraint(item: subview, attribute: NSLayoutAttribute.Bottom, relatedBy: NSLayoutRelation.Equal, toItem: self.bottomLayoutGuide, attribute: NSLayoutAttribute.Top, multiplier: 1, constant: 0),
            NSLayoutConstraint(item: subview, attribute: NSLayoutAttribute.Leading, relatedBy: NSLayoutRelation.Equal, toItem: subview.superview, attribute: NSLayoutAttribute.Leading, multiplier: 1, constant: 0),
            NSLayoutConstraint(item: subview, attribute: NSLayoutAttribute.Trailing, relatedBy: NSLayoutRelation.Equal, toItem: subview.superview, attribute: NSLayoutAttribute.Trailing, multiplier: 1, constant: 0)
        ])
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    func widgetPerformUpdateWithCompletionHandler(completionHandler: ((NCUpdateResult) -> Void)!) {
        // Perform any setup necessary in order to update the view.

        // If an error is encountered, use NCUpdateResult.Failed
        // If there's no update required, use NCUpdateResult.NoData
        // If there's an update, use NCUpdateResult.NewData

        completionHandler(NCUpdateResult.NewData)
    }
    
}
